### ISSUE TITLE
application crash on launch

### ISSUE THREAD

**Issue by parweb** [phoenixkonsole/transcendence#14]
transcendence : 2.0.0
macos : majave (10.14.6)

**Comment by parweb** [comment]
![demo](https://files-r6lc389je.now.sh/Kapture%202019-08-17%20at%203.47.27.gif)

**Comment by phoenixkonsole** [comment]
Very likely just a broken Blockchain.

**Comment by phoenixkonsole** [comment]
2.0.0.1 is also available

**Comment by parweb** [comment]
where can i find the directory off the blockchain on macos ? in order to delete ?

**Comment by phoenixkonsole** [comment]
it is in ~/Library/Application\ Support/Transcendence

at best you can use the Finder -> Go TO option
