### ISSUE TITLE
Wallet from release 1.1.0.0d not working on Win7 32 bit

### ISSUE THREAD

**Issue by joaaglo** [phoenixkonsole/transcendence#7]
Hi there,

first of all, I don't know if this is the best place to report the issue. I thought about posting it in the discord community too, but I finally decided to report it in here.

The last release does not work at all in my Win 7 32 bit PC, but the previous wallet 1.1.0.0 from July 2018 does. I have attached a screenshot with the error I get from Windows.

Could someone please take a look at this? I would like to update to the newest wallet in order to free some resources in my PC (the version I am using now needs more than 1GB RAM to run) and speed-up the connection and sync processes which are taking ages right now.

Thanks in advance and I hope win 7 32 bits is still supported.

Cheers.

![teloswallet1100d_notworking_win7-32bit](https://user-images.githubusercontent.com/8059098/53621462-e286f600-3bf6-11e9-9043-3198a5039f3d.png)

**Comment by phoenixkonsole** [comment]
Hi,
we are currently working on another small update which is not mandatory but it will include a DNS seed , we will ensure to offer 32Bit versions as well. For know you can try to reduce the connections by adding maxconnections=32 to the transcendence.conf
You can also add dbcache=50 to half the RAM demand. But doing so, extends synching time.

**Comment by phoenixkonsole** [comment]
The new 1.1.0.1 is again also available as 32Bit version
